item {
  id: 1
  name: 'stop'
}
item {
  id: 2
  name: 'speed_limit_20'
}

item {
  id: 3
  name: 'speed_limit_30'
}

item {
  id: 4
  name: 'speed_limit_50'
}

item {
  id: 5
  name: 'speed_limit_60'
}

item {
  id: 6
  name: 'speed_limit_70'
}

item {
  id: 7
  name: 'speed_limit_80'
}

item {
  id: 8
  name: 'speed_limit_100'
}

item {
  id: 9
  name: 'speed_limit_120'
}